# ISYS2407 Information Systems Solutions & Design

# Assignment 3 

# Feature Selection

#### Student name:  Hewa Pattinige Kemith Nanayakkara

#### Student number: S3758840




# 1 Import libraries

In [1]:
# Library for pickling
import joblib

# Also need pandas and nympy for some tasks
import pandas as pd
import numpy as np

# Library for splitting the data into train and test sets
from sklearn.model_selection import train_test_split 

# Library for replacing labels with numbers
from sklearn.preprocessing import LabelEncoder

# Libraries to select k best features
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


# 2 Load the cleaned data set

#### Pickled file must exist in your folder

In [2]:
employeeattrition_df = joblib.load('employeeattrition.pkl')   

In [3]:
# Check
employeeattrition_df.head()

age    business_travel  daily_rate              department  \
0   41      Travel_Rarely        1102                   Sales   
1   49  Travel_Frequently         279  Research & Development   
2   37      Travel_Rarely        1373  Research & Development   
3   33  Travel_Frequently        1392  Research & Development   
4   27      Travel_Rarely         591  Research & Development   

   distance_from_home  education education_field environment_satisfaction  \
0                   1          2   Life Sciences              Unsatisfied   
1                   8          1   Life Sciences                Satisfied   
2                   2          2           Other           Very Satisfied   
3                   3          4   Life Sciences           Very Satisfied   
4                   2          1         Medical         Very Unsatisfied   

   gender  hourly_rate  ...  relationship_satisfaction  stock_option_level  \
0  Female           94  ...           Very Unsatisfied                   0   
1    Male           61  ...             Very Satisfied                   1   
2    Male           92  ...                Unsatisfied                   0   
3  Female           56  ...                  Satisfied                   0   
4    Male           40  ...             Very Satisfied                   1   

  total_working_years training_times_last_year     work_life_balance  \
0                   8                        0  Extremely Unbalanced   
1                  10                        3              Balanced   
2                   7                        3              Balanced   
3                   8                        3              Balanced   
4                   6                        3              Balanced   

   years_at_company  years_in_current_role  years_since_last_promotion  \
0                 6                      4                           0   
1                10                      7                           1   
2                 0                      0                           0   
3                 8                      7                           3   
4                 2                      2                           2   

  years_with_curr_manager  attrition  
0                       5          1  
1                       7          0  
2                       0          1  
3                       0          0  
4                       2          0  

[5 rows x 31 columns]

In [4]:
# Check
print(employeeattrition_df.shape)
print(employeeattrition_df.columns)

(1470, 31)
Index(['age', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field',
       'environment_satisfaction', 'gender', 'hourly_rate', 'job_involvement',
       'job_level', 'job_role', 'job_satisfaction', 'marital_status',
       'monthly_income', 'monthly_rate', 'num_companies_worked', 'overtime',
       'percent_salary_hike', 'performance_rating',
       'relationship_satisfaction', 'stock_option_level',
       'total_working_years', 'training_times_last_year', 'work_life_balance',
       'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager', 'attrition'],
      dtype='object')


# 3 Split the data into training and testing set

In [5]:
# Store the features in variable X (uppercase as there are multiple features)
# Features are variables that affect the target/label
# So, it's all the columns excluding the target column
feature_cols = ['age', 'business_travel', 'daily_rate', 'department',
       'distance_from_home', 'education', 'education_field',
       'environment_satisfaction', 'gender', 'hourly_rate', 'job_involvement',
       'job_level', 'job_role', 'job_satisfaction', 'marital_status',
       'monthly_income', 'monthly_rate', 'num_companies_worked', 'overtime',
       'percent_salary_hike', 'performance_rating',
       'relationship_satisfaction', 'stock_option_level',
       'total_working_years', 'training_times_last_year', 'work_life_balance',
       'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager']

X = employeeattrition_df[feature_cols]
#print('X:\n', X)

# Store the labels/target in variable y (lower case as its a single value)
y = employeeattrition_df['attrition']
#print('y:\n', y)

# Split into train/test set
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, # keep 20% for testing
                                                    random_state=2 # pass an int for reproducible rtesult
                                                    )

# 4 Feature selection - trial-and-error process

#### Must be done after the data is split into training and testing sets and before scaling and on the training set only

In [6]:
X_train.shape

(1176, 30)

In [7]:
from sklearn.preprocessing import LabelEncoder
# 1. Select the columns to label encode
columns_to_encode = [
    'business_travel', 'department', 'gender',
    'education_field', 'environment_satisfaction', 'job_role',
    'job_satisfaction', 'marital_status', 'overtime', 
    'relationship_satisfaction', 'work_life_balance'
]

# 2. Make copy of the training and testing sets fix the issue below
X_train = X_train.copy()
X_test = X_test.copy()

# 3. Instantiate a LabelEncoder
encoder = LabelEncoder()

# 4. Fit the encoder on the training column and transform the training and testing columns
for col in columns_to_encode:
    # First fit the encoder to the training data
    encoder.fit(X_train[col])
    # Then transform both the training and the testing sets
    X_train[col] = encoder.transform(X_train[col])
    X_test[col] = encoder.transform(X_test[col])

# Check
X_train.head()

age  business_travel  daily_rate  department  distance_from_home  \
285    37                2        1372           1                   1   
194    45                0        1195           1                   2   
323    28                2        1157           1                   2   
1015   34                1         560           1                   1   
1003   25                2         949           1                   1   

      education  education_field  environment_satisfaction  gender  \
285           3                1                         2       0   
194           2                3                         3       1   
323           4                3                         3       1   
1015          4                4                         2       1   
1003          3                5                         3       1   

      hourly_rate  ...  performance_rating  relationship_satisfaction  \
285            42  ...                   3                          1   
194            65  ...                   4                          2   
323            84  ...                   3                          2   
1015           91  ...                   3                          0   
1003           81  ...                   3                          1   

      stock_option_level  total_working_years  training_times_last_year  \
285                    0                   17                         3   
194                    1                   22                         1   
323                    0                    5                         4   
1015                   2                   10                         2   
1003                   1                    7                         2   

      work_life_balance  years_at_company  years_in_current_role  \
285                   0                17                     12   
194                   0                20                      8   
323                   3                 3                      2   
1015                  0                 4                      3   
1003                  3                 3                      2   

      years_since_last_promotion  years_with_curr_manager  
285                            5                        7  
194                           11                        8  
323                            2                        2  
1015                           1                        3  
1003                           0                        2  

[5 rows x 30 columns]

## 4.1 Attempt 1

In [8]:
# This is a trial and error process
# First let's try k=25
X_selected = SelectKBest(chi2, k=25).fit_transform(X_train, y_train)

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 5 rows of the selected features
print(X_selected[:5])

# Print the first 5 rows of all the features in the dataset
X_train.iloc[:,:30].head()

<class 'numpy.ndarray'>
(1176, 25)
[[   37  1372     1     1     2     0    42     3     1     6     2     2
   2115 15881     1     0     1     0    17     3     0    17    12     5
      7]
 [   45  1195     1     2     3     1    65     2     4     3     2     1
   4919 20462     9     0     2     1    22     1     0    20     8    11
      8]
 [   28  1157     1     2     3     1    84     1     1     6     2     1
   3464 24737     5     1     2     0     5     4     3     3     2     2
      2]
 [   34   560     1     1     2     1    91     3     1     6     3     0
   2996 20284     5     0     0     2    10     2     0     4     3     1
      3]
 [   25   949     1     1     3     1    81     3     1     2     2     1
   3229  4910     4     0     1     1     7     2     3     3     2     0
      2]]


age  business_travel  daily_rate  department  distance_from_home  \
285    37                2        1372           1                   1   
194    45                0        1195           1                   2   
323    28                2        1157           1                   2   
1015   34                1         560           1                   1   
1003   25                2         949           1                   1   

      education  education_field  environment_satisfaction  gender  \
285           3                1                         2       0   
194           2                3                         3       1   
323           4                3                         3       1   
1015          4                4                         2       1   
1003          3                5                         3       1   

      hourly_rate  ...  performance_rating  relationship_satisfaction  \
285            42  ...                   3                          1   
194            65  ...                   4                          2   
323            84  ...                   3                          2   
1015           91  ...                   3                          0   
1003           81  ...                   3                          1   

      stock_option_level  total_working_years  training_times_last_year  \
285                    0                   17                         3   
194                    1                   22                         1   
323                    0                    5                         4   
1015                   2                   10                         2   
1003                   1                    7                         2   

      work_life_balance  years_at_company  years_in_current_role  \
285                   0                17                     12   
194                   0                20                      8   
323                   3                 3                      2   
1015                  0                 4                      3   
1003                  3                 3                      2   

      years_since_last_promotion  years_with_curr_manager  
285                            5                        7  
194                           11                        8  
323                            2                        2  
1015                           1                        3  
1003                           0                        2  

[5 rows x 30 columns]

## 4.2 Attempt 2

In [9]:
# Try k=20
X_selected = SelectKBest(chi2, k=20).fit_transform(X_train, y_train)

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 5 rows of the selected features
print(X_selected[:5])

# Print the first 5 rows of all the features in the dataset
X_train.iloc[:,:30].head()

<class 'numpy.ndarray'>
(1176, 20)
[[   37  1372     1     2    42     3     1     6     2  2115 15881     1
      0     0    17     3     0    17    12     7]
 [   45  1195     2     3    65     2     4     3     1  4919 20462     9
      0     1    22     1     0    20     8     8]
 [   28  1157     2     3    84     1     1     6     1  3464 24737     5
      1     0     5     4     3     3     2     2]
 [   34   560     1     2    91     3     1     6     0  2996 20284     5
      0     2    10     2     0     4     3     3]
 [   25   949     1     3    81     3     1     2     1  3229  4910     4
      0     1     7     2     3     3     2     2]]


age  business_travel  daily_rate  department  distance_from_home  \
285    37                2        1372           1                   1   
194    45                0        1195           1                   2   
323    28                2        1157           1                   2   
1015   34                1         560           1                   1   
1003   25                2         949           1                   1   

      education  education_field  environment_satisfaction  gender  \
285           3                1                         2       0   
194           2                3                         3       1   
323           4                3                         3       1   
1015          4                4                         2       1   
1003          3                5                         3       1   

      hourly_rate  ...  performance_rating  relationship_satisfaction  \
285            42  ...                   3                          1   
194            65  ...                   4                          2   
323            84  ...                   3                          2   
1015           91  ...                   3                          0   
1003           81  ...                   3                          1   

      stock_option_level  total_working_years  training_times_last_year  \
285                    0                   17                         3   
194                    1                   22                         1   
323                    0                    5                         4   
1015                   2                   10                         2   
1003                   1                    7                         2   

      work_life_balance  years_at_company  years_in_current_role  \
285                   0                17                     12   
194                   0                20                      8   
323                   3                 3                      2   
1015                  0                 4                      3   
1003                  3                 3                      2   

      years_since_last_promotion  years_with_curr_manager  
285                            5                        7  
194                           11                        8  
323                            2                        2  
1015                           1                        3  
1003                           0                        2  

[5 rows x 30 columns]

## 4.3 Attempt 3

In [10]:
# Try k=12
X_selected = SelectKBest(chi2, k=12).fit_transform(X_train, y_train)

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 5 rows of the selected features
print(X_selected[:5])

# Print the first 5 rows of all the features in the dataset
X_train.iloc[:,:30].head()

<class 'numpy.ndarray'>
(1176, 12)
[[   37  1372     1     2  2115 15881     0     0    17    17    12     7]
 [   45  1195     2     1  4919 20462     0     1    22    20     8     8]
 [   28  1157     2     1  3464 24737     1     0     5     3     2     2]
 [   34   560     1     0  2996 20284     0     2    10     4     3     3]
 [   25   949     1     1  3229  4910     0     1     7     3     2     2]]


age  business_travel  daily_rate  department  distance_from_home  \
285    37                2        1372           1                   1   
194    45                0        1195           1                   2   
323    28                2        1157           1                   2   
1015   34                1         560           1                   1   
1003   25                2         949           1                   1   

      education  education_field  environment_satisfaction  gender  \
285           3                1                         2       0   
194           2                3                         3       1   
323           4                3                         3       1   
1015          4                4                         2       1   
1003          3                5                         3       1   

      hourly_rate  ...  performance_rating  relationship_satisfaction  \
285            42  ...                   3                          1   
194            65  ...                   4                          2   
323            84  ...                   3                          2   
1015           91  ...                   3                          0   
1003           81  ...                   3                          1   

      stock_option_level  total_working_years  training_times_last_year  \
285                    0                   17                         3   
194                    1                   22                         1   
323                    0                    5                         4   
1015                   2                   10                         2   
1003                   1                    7                         2   

      work_life_balance  years_at_company  years_in_current_role  \
285                   0                17                     12   
194                   0                20                      8   
323                   3                 3                      2   
1015                  0                 4                      3   
1003                  3                 3                      2   

      years_since_last_promotion  years_with_curr_manager  
285                            5                        7  
194                           11                        8  
323                            2                        2  
1015                           1                        3  
1003                           0                        2  

[5 rows x 30 columns]

## 4.4 Attempt 4

In [11]:
# Try k=8
X_selected = SelectKBest(chi2, k=8).fit_transform(X_train, y_train)

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 5 rows of the selected features
print(X_selected[:5])

# Print the first 5 rows of all the features in the dataset
X_train.iloc[:,:20].head()

<class 'numpy.ndarray'>
(1176, 8)
[[   37  1372  2115 15881    17    17    12     7]
 [   45  1195  4919 20462    22    20     8     8]
 [   28  1157  3464 24737     5     3     2     2]
 [   34   560  2996 20284    10     4     3     3]
 [   25   949  3229  4910     7     3     2     2]]


age  business_travel  daily_rate  department  distance_from_home  \
285    37                2        1372           1                   1   
194    45                0        1195           1                   2   
323    28                2        1157           1                   2   
1015   34                1         560           1                   1   
1003   25                2         949           1                   1   

      education  education_field  environment_satisfaction  gender  \
285           3                1                         2       0   
194           2                3                         3       1   
323           4                3                         3       1   
1015          4                4                         2       1   
1003          3                5                         3       1   

      hourly_rate  job_involvement  job_level  job_role  job_satisfaction  \
285            42                3          1         6                 2   
194            65                2          4         3                 2   
323            84                1          1         6                 2   
1015           91                3          1         6                 3   
1003           81                3          1         2                 2   

      marital_status  monthly_income  monthly_rate  num_companies_worked  \
285                2            2115         15881                     1   
194                1            4919         20462                     9   
323                1            3464         24737                     5   
1015               0            2996         20284                     5   
1003               1            3229          4910                     4   

      overtime  percent_salary_hike  
285          0                   12  
194          0                   23  
323          1                   13  
1015         0                   14  
1003         0                   11

# 4.1 What are the best features for building predictive models?

The best feautres are: 
    age, 
    daily_rate, 
    monthly_income, 
    monthly_rate, 
    total_working_years,
    years_at_company,
    years_in_current_role,
    years_with_current_manager.